run:
  concurrency: 4
  timeout: 3m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: readonly
  skip-files:
    - "/*/*mock*.go"
    - "/*/*test.go"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    check-shadowing: true
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    enable-all: true
    disable-all: false
    disable:
      - fieldalignment
  unused:
    check-exported: true
  goimports:
    local-prefixes: crud-transaction/
  nakedret:
    max-func-lines: 10
  goconst:
    min-len: 3
    min-occurrences: 2
  gofmt:
    simplify: true
  maligned:
    suggest-new: true
  fieldalignment:
    suggest-new: true
  tagliatelle:
    case:
      rules:
        json: snake
  lll:
    line-length: 160
  revive:
    ignore-generated-header: true
    severity: warning
    formatter: friendly
    confidence: 0.8
    errorCode: 0
    warningCode: 0
    rules:
      - name: atomic
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: dot-imports
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: if-return
      - name: increment-decrement
      - name: var-naming
      - name: var-declaration
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: time-naming
      - name: unexported-return
      - name: indent-error-flow
      - name: errorf
      - name: empty-block
      - name: superfluous-else
      - name: unused-parameter
      - name: unreachable-code
      - name: redefines-builtin-id
      - name: context-as-argument
      - name: cyclomatic
        arguments: 7
      - name: empty-block
      - name: add-constant
      - name: empty-lines
      - name: cognitive-complexity
        arguments: 7
      - name: line-length-limit
        arguments: 160

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - copyloopvar
    - exhaustive
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gofmt
    - goimports
    - revive
    - mnd
    - goprintffuncname
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - depguard
  fast: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
  new-from-rev: origin/master
  exclude-rules:
    - path: test
      linters:
        - dupl
        - funlen
        - exhaustivestruct
        - fieldalignment
        - scopelint
        - testpackage
        - paralleltest
